name: gpt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  auto_route: ^5.0.4
  cloud_firestore: ^4.9.2
  dartz: ^0.10.1
  day_night_switcher: ^0.2.0+1
  device_info_plus: ^8.1.0
  dio: ^5.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  flutter_adaptive_ui: ^0.8.0+1
  flutter_bloc: ^8.1.3
  flutter_polyline_points: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_image_map: ^0.9.3
  flutter_localizations:
    sdk: flutter
  form_field_validator: ^1.1.0
  full_screen_image: ^2.0.0
  geolocator: ^10.0.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.5.0
  google_fonts: ^4.0.3
  image_picker: ^1.0.4
  injectable: ^2.1.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  location: ^5.0.3
  multiple_result: ^4.0.0
  permission_handler: ^11.0.0
  path_provider: ^2.0.13
  slide_countdown: ^0.5.0
  shared_preferences: ^2.2.1
  url_strategy: ^0.2.0
  uuid: ^4.0.0
  mask_text_input_formatter: ^2.5.0
  flutter_secure_storage: ^8.1.0
  floating_action_bubble: ^1.1.4
dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.1.6
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  lints: ^2.0.1
dependency_overrides:
  intl: ^0.17.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/fonts/google_fonts/
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  localizely:
    project_id: "286"
