// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```'
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdDm78epVvv7KutlWNGg9rMRuv_jLPZ7c',
    appId: '1:903726331632:web:004c04e7fc9c342f397435',
    messagingSenderId: '903726331632',
    projectId: 'todo-list-case-study',
    authDomain: 'todo-list-case-study.firebaseapp.com',
    storageBucket: 'todo-list-case-study.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj49AxnTRbeVQz6BWxrpB4_jCXt6iK7d8',
    appId: '1:903726331632:android:206d71f27da76dd0397435',
    messagingSenderId: '903726331632',
    projectId: 'todo-list-case-study',
    storageBucket: 'todo-list-case-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60JNTah-Gf7M3khPBzSAjxl_oY807Fp0',
    appId: '1:903726331632:ios:a765553a69ce4369397435',
    messagingSenderId: '903726331632',
    projectId: 'todo-list-case-study',
    storageBucket: 'todo-list-case-study.appspot.com',
    iosBundleId: 'com.example.todoListCaseStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60JNTah-Gf7M3khPBzSAjxl_oY807Fp0',
    appId: '1:903726331632:ios:ee18b5458bc3ef59397435',
    messagingSenderId: '903726331632',
    projectId: 'todo-list-case-study',
    storageBucket: 'todo-list-case-study.appspot.com',
    iosBundleId: 'com.example.todoListCaseStudy.RunnerTests',
  );
}
