// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Xc8crfqDinDtoMWscinTh43Q7RavJB8',
    appId: '1:68491047989:web:3a6c47446da9559be02d7c',
    messagingSenderId: '68491047989',
    projectId: 'flutter-gpt-until',
    authDomain: 'flutter-gpt-until.firebaseapp.com',
    storageBucket: 'flutter-gpt-until.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLfhDdafLARXINPEa8k4N53vJWmmvpOc',
    appId: '1:68491047989:android:38999f7fd47bf6b3e02d7c',
    messagingSenderId: '68491047989',
    projectId: 'flutter-gpt-until',
    storageBucket: 'flutter-gpt-until.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGhc7VKQVFfnHs3Rf0FUWVL3Sx0QxXC8',
    appId: '1:68491047989:ios:eec07528ec978df2e02d7c',
    messagingSenderId: '68491047989',
    projectId: 'flutter-gpt-until',
    storageBucket: 'flutter-gpt-until.appspot.com',
    iosBundleId: 'com.example.gpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDGhc7VKQVFfnHs3Rf0FUWVL3Sx0QxXC8',
    appId: '1:68491047989:ios:b99dfb1bc332413de02d7c',
    messagingSenderId: '68491047989',
    projectId: 'flutter-gpt-until',
    storageBucket: 'flutter-gpt-until.appspot.com',
    iosBundleId: 'com.example.gpt.RunnerTests',
  );
}
